### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by ahenket**
Added complete translation to Dutch based on English input strings.

### CODE REVIEW

**Comment by sorincarbunaru** [comment]
Woow!!! Thank you for your contribution, Alexander! This is such a nice surprise. We really appreciate it.

**Comment by sorincarbunaru** [comment]
Our legal department contacted me and told me that, because you didn't use a Git sign-off, I need to explicitly ask you if you agree to us using your contribution in our add-on and distributing it under an Apache 2.0 License. You know... Technicalities... So, do you agree? 😃

**Comment by ahenket** [comment]
Absolutely. I just no idea what a signify was and the instruction were too elaborate for the time I had. Note: I was the original translator for Dutch for Oxygen as a whole before an agency took over some years ago.

Op 12 feb. 2021, om 15:22 heeft Sorin Carbunaru <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



Our legal department contacted me and told me that, because you didn't use a Git sign-off, I need to explicitly ask you if you agree to us using your contribution in our add-on and distributing it under an Apache 2.0 License. You know... Technicalities... So, do you agree? 😃

**Comment by sorincarbunaru** [comment]
Hi Alexander! I added some new messages and modified some older ones. Could you please translate them into Dutch, if you can find some time, and create a new pull request? Don't forget to sign-off the commit, or at least clearly mention that you allow us to use and distribute your changes under Apache 2.0 License :).

**Pull request merged**
